### ISSUE TITLE
粘液科技附属异域花园不兼容

### ISSUE THREAD

**Issue by dandanlong123** [StarWishsama/ExoticGarden-CN#5]
## 描述 (必须)
最新版粘液加黏土dev6无法使用最新版异域

## 复现步骤 (必须)
![Screenshot_20200616-084900_JuiceSSH](https://user-images.githubusercontent.com/54028891/84719717-a07df100-afae-11ea-8983-1d455d6aca51.jpg)

## 服务器 Log / Slimefun 自带的错误报告
08:47:46 INFO]: [ExoticGarden] Enabling ExoticGarden vDEV - 51 (git 17d2d47d)
[08:47:46 ERROR]: Error occurred while enabling ExoticGarden vDEV - 51 (git 17d2d47d) (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/cscorelib2/reflection/ReflectionUtils
        at io.github.thebusybiscuit.exoticgarden.ExoticGarden.onEnable(ExoticGarden.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-1.15.2.jar:git-Paper-98]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[Paper-1.15.2.jar:git-Paper-98]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[Paper-1.15.2.jar:git-Paper-98]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[Paper-1.15.2.jar:git-Paper-98]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[Paper-1.15.2.jar:git-Paper-98]

## 服务器环境 (必须)
![20200616_090149](https://user-images.githubusercontent.com/54028891/84720317-55fd7400-afb0-11ea-9666-7609d19859de.jpg)

 - Minecraft 版本:1.15.2
 - Slimefun 版本:Slimefun-v4.3-WEEKLY-200614
 - CS-CoreLib 版本:CS-CoreLib - DEV 85 (git 4a7fc)

**Comment by stydxm** [comment]
用这个看看[https://github.com/StarWishsama/ExoticGarden-CN/releases/latest](https://github.com/StarWishsama/ExoticGarden-CN/releases/latest)
